"""Exec Statuses supported by Gizo"""
CANCELLED   = "CANCELLED"
""""cancelled by sender"""
QUEUED      = "QUEUED"  
""" job added to job queue"""
TIMEOUT     = "TIMEOUT" 
"""job timed out"""
RUNNING     = "RUNNING"   
"""job being executed"""
FINISHED    = "FINISHED"   
"""job done"""
RETRYING    = "RETRYING"
"""job retrying"""
DISPATHCHED = "DISPATCHED" 
"""job dispatched to worker"""
STARTED     = "STARTED"
"""job received by dispatcher (prior to dispatch)"""
